package all

// planned returns registry entries for mistakes that are not yet enforced
// by an Analyzer. They appear in the generated RULES.md as the coverage
// roadmap so engineers can see the full landscape, not just what's live.
func planned() []Entry {
	return []Entry{
		// --- Workflow Limits (mostly RuntimeOnly) -------------------------
		{Name: "history-event-overflow", Category: CategoryWorkflowLimits, Status: StatusRuntimeOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#overflowing-workflow-history-length",
			Summary:    "Workflow history exceeds maximum event count. Detect via metrics, not source."},
		{Name: "history-bytes-overflow", Category: CategoryWorkflowLimits, Status: StatusRuntimeOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#overflowing-workflow-history-bytes",
			Summary:    "Workflow history exceeds maximum size. Detect via metrics."},
		{Name: "individual-payload-overflow", Category: CategoryWorkflowLimits, Status: StatusRuntimeOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#overflowing-maximum-individual-payload-size",
			Summary:    "Individual payload exceeds maximum size."},
		{Name: "shard-contention", Category: CategoryWorkflowLimits, Status: StatusRuntimeOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#shard-contention-due-to-concurrent-updates",
			Summary:    "Concurrent updates contend on a single shard."},
		{Name: "naive-batch-processing", Category: CategoryWorkflowLimits, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#naive-batch-processing-implementations",
			Summary:    "Batch processing implemented as a single workflow with too many activities."},
		{Name: "exceeding-task-timeout", Category: CategoryWorkflowLimits, Status: StatusRuntimeOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#exceeding-10s-task-timeout",
			Summary:    "Workflow task exceeds 10s default timeout."},

		// --- Workflow Replay (mix) ----------------------------------------
		{Name: "no-versioning", Category: CategoryReplay, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-using-workflow-versioningpatching",
			Summary:    "Detect breaking workflow changes without GetVersion guard. Planned for Batch 6."},
		{Name: "incorrect-patching", Category: CategoryReplay, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#incorrect-workflow-patching",
			Summary:    "GetVersion called with wrong version numbers / branch removed prematurely."},
		{Name: "replay-misunderstanding", Category: CategoryReplay, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#thinking-replay-means-re-running-activities",
			Summary:    "Conceptual: replay does not re-run activities."},
		{Name: "expensive-workflow-computation", Category: CategoryReplay, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#performing-expensive-computation-in-workflow-code",
			Summary:    "Detect heavy CPU work (loops, hashing, JSON parsing) in workflow code."},
		{Name: "lossy-serialization", Category: CategoryReplay, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#lossy-payload-serializationdeserialization",
			Summary:    "Payload encoding loses data (precision, ordering)."},
		{Name: "breaking-payload-changes", Category: CategoryReplay, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#breaking-changes-to-payloads",
			Summary:    "Detect non-additive changes to workflow input/output structs."},
		{Name: "no-sdk-observability", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-using-temporal-sdk-for-observability",
			Summary:    "Use workflow.GetLogger / GetMetricsHandler, not stdlib log/metrics."},
		{Name: "no-replay-debug", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-using-workflow-replay-for-debugging",
			Summary:    "Use replay tooling for debugging non-determinism."},
		{Name: "history-modifying-interceptor", Category: CategoryReplay, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#modifying-workflow-history-in-interceptors",
			Summary:    "Interceptors that alter history corrupt replay."},

		// --- Timeouts and Retries -----------------------------------------
		{Name: "workflow-timeout-cleanup", Category: CategoryTimeouts, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#assuming-workflow-timeouts-allow-graceful-cleanup",
			Summary:    "Workflow timeouts terminate, they don't cancel — no graceful cleanup."},
		{Name: "too-short-timeouts", Category: CategoryTimeouts, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#setting-too-short-timeouts",
			Summary:    "StartToCloseTimeout < downstream p99 latency causes false retries."},

		// --- Cancellation -------------------------------------------------
		{Name: "activity-vs-workflow-cancel", Category: CategoryCancellation, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#assuming-activity-cancellation-means-workflow-cancellation",
			Summary:    "Cancelling an activity does not cancel its workflow."},
		{Name: "no-parent-close-policy", Category: CategoryCancellation, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-using-parentclosepolicy",
			Summary:    "Child workflow lacks ParentClosePolicy — orphaned on parent close."},
		{Name: "deadlock-on-cancel", Category: CategoryCancellation, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#deadlocking-when-workflow-canceled",
			Summary:    "Cancelled workflow blocks on operations that themselves require non-cancelled context."},
		{Name: "no-disconnected-context", Category: CategoryCancellation, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-using-disconnected-context-for-cleanup",
			Summary:    "Cleanup activities run with cancelled context, never executing."},

		// --- Software Design ----------------------------------------------
		{Name: "non-idempotent-activity", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-making-activities-idempotent",
			Summary:    "Activities can run more than once on retry. Caller must make them idempotent."},
		{Name: "ignored-input-payload", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-leveraging-workflow-inputresponse-payloads",
			Summary:    "Workflow uses signals/queries where input/result payloads suffice."},
		{Name: "multiple-input-payloads", Category: CategoryDesign, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#using-multiple-inputresponse-payloads",
			Summary:    "Workflows should take a single input/output struct, not variadic args."},
		{Name: "monolithic-workflow", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#doing-too-many-things-in-one-workflow",
			Summary:    "Too many activity types in one workflow — split into child workflows."},
		{Name: "over-using-activities", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#over-using-activities",
			Summary:    "Trivial pure functions wrapped as activities incur unnecessary checkpoints."},
		{Name: "unnecessary-workflow", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#unnecessary-workflow-usage",
			Summary:    "CRUD operations don't need workflow durability."},
		{Name: "no-heartbeat-details", Category: CategoryDesign, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-using-activity-heartbeat-details",
			Summary:    "Long activities should heartbeat resumption state."},
		{Name: "no-continue-as-new", Category: CategoryDesign, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-using-continueasnew",
			Summary:    "Long-lived workflows should call ContinueAsNew to bound history."},
		{Name: "signal-drain-missing", Category: CategoryDesign, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-draining-signals-before-completing",
			Summary:    "Workflow completes while signals are pending — signals lost."},
		{Name: "list-workflow-dependency", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#depending-on-listworkflow-api",
			Summary:    "ListWorkflow is for ops, not application logic."},
		{Name: "work-outside-workflow", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#doing-work-outside-workflows",
			Summary:    "Operations outside workflow lose durability guarantees."},
		{Name: "queue-as-workflow", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#wrapping-a-queue-with-a-workflow",
			Summary:    "Don't use a workflow to wrap a queue — use a queue."},
		{Name: "unnecessary-child-workflow", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#unnecessary-child-workflows",
			Summary:    "Child workflows add complexity without benefit when activities suffice."},
		{Name: "custom-task-orchestration", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#custom-task-orchestration-frameworks",
			Summary:    "Don't reinvent Temporal on top of Temporal."},
		{Name: "local-activity-misuse", Category: CategoryDesign, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#using-local-activities",
			Summary:    "Local activities have many limits; reach for regular activities first."},
		{Name: "polling-workflow-result", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#polling-workflow-results",
			Summary:    "Polling workflow result via DescribeWorkflow is wasteful."},
		{Name: "start-workflow-from-activity", Category: CategoryDesign, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#starting-workflows-from-activities",
			Summary:    "Activities should not start workflows — break the abstraction."},
		{Name: "signal-update-ordering", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#assuming-signalsupdates-receive-in-order",
			Summary:    "Signals/updates are not strictly ordered."},
		{Name: "workflow-id-collision", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-properly-scoping-semantic-workflow-ids",
			Summary:    "Workflow IDs must be properly scoped to avoid collisions."},
		{Name: "no-wait-for-child-start", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-waiting-for-child-workflows-to-start",
			Summary:    "Don't disconnect from child without first awaiting GetChildWorkflowExecution."},
		{Name: "polling-loop-in-workflow", Category: CategoryDesign, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#writing-polling-loops-in-workflow-code",
			Summary:    "for { sleep; check; } in workflow — use signals or timers."},
		{Name: "querying-closed-workflow", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#querying-closed-workflows",
			Summary:    "Closed workflows have no live state to query."},
		{Name: "sensitive-data-in-history", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#storing-sensitive-data-in-history",
			Summary:    "Workflow history is an audit trail; redact secrets."},
		{Name: "fallible-local-activity", Category: CategoryDesign, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#fallible-local-activities",
			Summary:    "Local activities don't retry the same way; design for that."},

		// --- Operations ---------------------------------------------------
		{Name: "terminate-vs-cancel", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#terminating-rather-than-canceling",
			Summary:    "Terminate skips cancellation cleanup — prefer cancel."},
		{Name: "no-stsl-monitoring", Category: CategoryOperations, Status: StatusRuntimeOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-monitoring-stsl",
			Summary:    "Schedule-to-Start latency must be observed."},
		{Name: "no-sync-match-monitoring", Category: CategoryOperations, Status: StatusRuntimeOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-monitoring-sync-match-rate",
			Summary:    "Sync-match rate is a key worker-health metric."},
		{Name: "no-autotuning", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-enabling-autotuning",
			Summary:    "Worker autotuning is off by default; turn it on."},
		{Name: "no-workflow-reset", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-knowing-about-workflow-reset",
			Summary:    "Workflow reset is the recovery primitive when replay breaks."},
		{Name: "no-batch-ops", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-knowing-about-batch-operations-api",
			Summary:    "Batch operations API exists for bulk admin tasks."},
		{Name: "no-graceful-drain", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-draining-activity-tasks-before-shutdown",
			Summary:    "Workers should drain on SIGTERM."},
		{Name: "decode-payloads-in-history-export", Category: CategoryOperations, Status: StatusDocOnly,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#downloading-history-with-decodepayloads-enabled",
			Summary:    "Don't export history with payloads decoded in plaintext."},
		{Name: "no-replay-validation", Category: CategoryOperations, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#not-validating-replay-safety-before-deployments",
			Summary:    "Run replay tests in CI to catch non-deterministic changes pre-deploy."},

		// --- Other --------------------------------------------------------
		{Name: "wrong-task-queue", Category: CategoryOther, Status: StatusPlanned,
			MistakeURL: "https://github.com/jlegrone/100-temporal-mistakes#starting-workflows-on-wrong-task-queue",
			Summary:    "Mismatch between client task queue and worker registration."},
	}
}
