// Command gen-rules emits tools/temporallint/RULES.md from the
// all.Registry() metadata. Run via `go generate ./...` or directly:
//
//	go run ./tools/temporallint/cmd/gen-rules > tools/temporallint/RULES.md
//
// CI fails if the generated file is stale.
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/mattconzen/temporallint/all"
)

func main() {
	if err := write(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func write(w io.Writer) error {
	if _, err := fmt.Fprint(w, header); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| Rule | Category | Status | Source |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| --- | --- | --- | --- |"); err != nil {
		return err
	}
	for _, e := range all.Registry() {
		if _, err := fmt.Fprintf(w, "| `%s` | %s | %s | [link](%s) |\n",
			e.Name, e.Category, e.Status, e.MistakeURL); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprint(w, footer); err != nil {
		return err
	}
	return nil
}

const header = `<!-- GENERATED by tools/temporallint/cmd/gen-rules. DO NOT EDIT. -->
# temporallint coverage

This table is the authoritative inventory of [Temporal anti-patterns](https://github.com/jlegrone/100-temporal-mistakes) that temporallint knows about.

Status legend:
- **Implemented** — static analyzer is wired up and emits diagnostics.
- **RuntimeImplemented** — runtime check is wired up; verified via ` + "`temporallint runtime`" + `.
- **Planned** — on the roadmap; entry exists so the gap is visible.
- **RuntimeOnly** — only detectable at runtime; no check has been written yet (typically requires metrics scraping rather than SDK calls).
- **DocOnly** — design or process concern; surfaced for awareness.

`

const footer = `

## Running runtime checks

Static analyzers run via ` + "`go test ./tools/temporallint/...`" + ` or via the binary
on Go packages: ` + "`temporallint ./...`" + `. Runtime checks need a live Temporal
server. Invoke them via the same binary with the ` + "`runtime`" + ` subcommand:

    temporallint runtime --address localhost:7233 --namespace default --since 24h

Authentication uses ` + "`--api-key`" + ` (env: ` + "`TEMPORAL_API_KEY`" + `) for Temporal Cloud
or any gateway with API-key support; without a key the dial is plain
gRPC, suitable for ` + "`temporal server start-dev`" + `. ` + "`--output=json`" + ` emits
machine-readable findings; ` + "`--fail-on=warn`" + ` makes any warn-tier finding
produce a non-zero exit code.

## Regenerating

    go run ./tools/temporallint/cmd/gen-rules > tools/temporallint/RULES.md
`
