// Command gen-rules emits tools/temporallint/RULES.md from the
// all.Registry() metadata. Run via `go generate ./...` or directly:
//
//	go run ./tools/temporallint/cmd/gen-rules > tools/temporallint/RULES.md
//
// CI fails if the generated file is stale.
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/mattconzen/monorepo/tools/temporallint/all"
)

func main() {
	if err := write(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func write(w io.Writer) error {
	if _, err := fmt.Fprint(w, header); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| Rule | Category | Status | Source |"); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "| --- | --- | --- | --- |"); err != nil {
		return err
	}
	for _, e := range all.Registry() {
		if _, err := fmt.Fprintf(w, "| `%s` | %s | %s | [link](%s) |\n",
			e.Name, e.Category, e.Status, e.MistakeURL); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprint(w, footer); err != nil {
		return err
	}
	return nil
}

const header = `<!-- GENERATED by tools/temporallint/cmd/gen-rules. DO NOT EDIT. -->
# temporallint coverage

This table is the authoritative inventory of [Temporal anti-patterns](https://github.com/jlegrone/100-temporal-mistakes) that temporallint knows about.

Status legend:
- **Implemented** — analyzer is wired up and emits diagnostics.
- **Planned** — on the roadmap; entry exists so the gap is visible.
- **RuntimeOnly** — only detectable at runtime (metrics / observability).
- **DocOnly** — design or process concern; surfaced for awareness.

`

const footer = `

Regenerate with:

    go run ./tools/temporallint/cmd/gen-rules > tools/temporallint/RULES.md
`
